### ISSUE TITLE
component/Text: Type 'number' is not assignable to type '"sm" | "base" | "lg" | "xl" | "md"'

### ISSUE THREAD

**Issue by mtnptrsn** [EQuimper/react-native-design-utility#5]
When passing a number to the size prop in the Text component I get this error: `Type 'number' is not assignable to type '"sm" | "base" | "lg" | "xl" | "md"'`

It is possible to add a number but the type is incorrect.

**Comment by EQuimper** [comment]
Perfect I will fix this, thank you

**Comment by EQuimper** [comment]
@mtnptrsn which version are you using ?

**Comment by mtnptrsn** [comment]
@EQuimper Sorry I was using an old version!
